name: Functions Build and Deploy

on:
  push:
    branches:
    - master
    paths:
    - api/**

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master
    
    - name: Setup .NET Core      
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100

    - name: 'Resolve Project Dependencies Using Dotnet'
      run: dotnet build --configuration Release --output ./output
      working-directory: api

    - uses: Azure/functions-action@v1
      id: fa
      with:
        app-name: buzzer-app-api
        package: 'api/output'
        publish-profile: ${{ secrets.SCM_CREDENTIALS }}

    